### ISSUE TITLE
Idea: redirect to file

### ISSUE THREAD

**Issue by adi-** [mherrmann/django-404-middleware#1]
Would be nice if the app could have an option to redirect output to file.

**Comment by mherrmann** [comment]
I'm not 100% what you mean by this; But either way - for my open source projects, contributions like yours in the form of "I have an idea" are of little use. I have limited time and no time to spend on developing vaguely expressed ideas, or to implement them. If you'd like to contribute, feel free to submit a Pull Request. Everything else just takes time that I don't have.
